### ISSUE TITLE
Unnecessary issue

### ISSUE THREAD

**Issue by volodymyr-kushnir** [yumsterr/bsaLectureGit#1]
Hey, @yumsterr, hola, how's it going?
Додав **issue** просто так, шоб було, тому можна ставити лейбл **won'tfix** і закривати.
Також, ммм, рекомендував би ще глянути [**лайфхаки і підказки**](https://github.com/volodymyr-kushnir/agenda). Як воно взагалі, получається?

**Comment by yumsterr** [comment]
Добрый день!
Все получается, да. Но закоммитила все с чужого компьютера и всюду подписан другой юзер. Это не проблема?

**Comment by volodymyr-kushnir** [comment]
@yumsterr нет никаких проблем, но нам нужно больше веток, хозяин...
Если смержить и потом залить, то зальется только `master`. Как насчет заапстримить несколько веток (ещё одну кроме мастера, допустим), затем создать **Pull Request** уже на **GitHub**'е и смержить уже здесь? Затем можна спуллить себе уже померженый `master`.

*(сделано в #3, успех)*

**Comment by yumsterr** [comment]
Ок, спасибо)
